//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportadorCamaraProcessIcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenca_deputado
    {
        public int idpresenca_deputado { get; set; }
        public int idSessao { get; set; }
        public int legislatura { get; set; }
        public int carteiraParlamentar { get; set; }
        public sbyte presenca { get; set; }
        public string justificativa { get; set; }
        public Nullable<sbyte> presencaExterna { get; set; }
    
        public virtual sessao_camara sessao_camara { get; set; }
    }
}
